import { Figurine } from './figurine';
  
export const FIGURINES: Figurine[] = [
    {
        id: 1,
        name: "Obélix",
        picture: "./assets/image/obelix.jpg",
        price: 25,
        description: "Obélix, notre gourmand guerrier",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 2,
        name: "Idéfix",
        picture: "./assets/image/idefix.jpg",
        price: 24,
        description: "Idéfix, notre ami fidèle",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 4 cm",
    },
    {
        id: 3,
        name: "Agecanonix",
        picture: "./assets/image/agecanonix.jpg",
        price: 20,
        description: "Agecanonix, notre relique",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 6 cm",
    },
    {
        id: 4,
        name: "Astérix",
        picture: "./assets/image/asterix.jpg",
        price: 25,
        description: "Astérix, notre guerrier",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 7 cm",
    },
    {
        id: 5,
        name: "Abraracourci",
        picture: "./assets/image/abraracourcix.jpg",
        price: 22,
        description: "Abraracourcix, notre chef",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 8 cm",
    },
    {
        id: 6,
        name: "Panoramix",
        picture: "./assets/image/panoramix.jpg",
        price: 22,
        description: "Panoramix, notre druide",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 7,
        name: "Falbala",
        picture: "./assets/image/falbala.jpg",
        price: 21,
        description: "Falbala, notre guerrière",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 9 cm",
    },
    {
        id: 8,
        name: "Romain",
        picture: "./assets/image/romain.jpg",
        price: 21,
        description: "Romain, jouet de nos gaulois",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 8 cm",
    }
   
];